export const FETCH_POSITIONS_FAILURE = 'FETCH_POSITIONS_FAILURE';
export const FETCH_POSITIONS_REQUEST = 'FETCH_POSITIONS_REQUEST';
export const FETCH_POSITIONS_SUCCESS = 'FETCH_POSITIONS_SUCCESS';
export const REMOVE_POSITION         = 'REMOVE_POSITION';
export const VIEW_POSITION           = 'VIEW_POSITION';
