export const FETCH_CONTRACTSVIEW_FAILURE = 'FETCH_CONTRACTSVIEW_FAILURE';
export const FETCH_CONTRACTSVIEW_REQUEST = 'FETCH_CONTRACTSVIEW_REQUEST';
export const FETCH_CONTRACTSVIEW_SUCCESS = 'FETCH_CONTRACTSVIEW_SUCCESS';
export const REMOVE_CONTRACTVIEW         = 'REMOVE_CONTRACTVIEW';
export const VIEW_CONTRACTVIEW           = 'VIEW_CONTRACTVIEW';
