export const FETCH_LOGINPAGE_REQUEST = 'FETCH_LOGINPAGE_REQUEST';
export const FETCH_LOGINPAGE_SUCCESS = 'FETCH_LOGINPAGE_SUCCESS';
export const FETCH_LOGINPAGE_FAILURE = 'FETCH_LOGINPAGE_FAILURE';
export const SET_MODAL_STATE         = 'SET_MODAL_STATE';
