export const FETCH_SYSTEMNOTES_FAILURE = 'FETCH_SYSTEMNOTES_FAILURE';
export const FETCH_SYSTEMNOTES_REQUEST = 'FETCH_SYSTEMNOTES_REQUEST';
export const FETCH_SYSTEMNOTES_SUCCESS = 'FETCH_SYSTEMNOTES_SUCCESS';
export const VIEW_SYSTEMNOTE           = 'VIEW_SYSTEMNOTE';
