export const FETCH_DEPARTMENTS_DICTS_REQUEST = 'FETCH_DEPARTMENTS_DICTS_REQUEST';
export const FETCH_DEPARTMENTS_DICTS_SUCCESS = 'FETCH_DEPARTMENTS_DICTS_SUCCESS';
export const FETCH_DEPARTMENTS_DICTS_FAILURE = 'FETCH_DEPARTMENTS_DICTS_FAILURE';
export const REMOVE_DEPARTMENT_DICT          = 'REMOVE_DEPARTMENT_DICT';
export const VIEW_DEPARTMENT_DICT            = 'VIEW_DEPARTMENT_DICT';

export const SET_CATEGORYMESSAGE = 'SET_CATEGORYMESSAGE';