export const FETCH_CONTRACTSEXCLUSIVE_FAILURE = 'FETCH_CONTRACTSEXCLUSIVE_FAILURE';
export const FETCH_CONTRACTSEXCLUSIVE_REQUEST = 'FETCH_CONTRACTSEXCLUSIVE_REQUEST';
export const FETCH_CONTRACTSEXCLUSIVE_SUCCESS = 'FETCH_CONTRACTSEXCLUSIVE_SUCCESS';
export const REMOVE_CONTRACTEXCLUSIVE         = 'REMOVE_CONTRACTEXCLUSIVE';
export const VIEW_CONTRACTEXCLUSIVE           = 'VIEW_CONTRACTEXCLUSIVE';
