export const FETCH_APARTMENTSRENT_FAILURE = 'FETCH_APARTMENTSRENT_FAILURE';
export const FETCH_APARTMENTSRENT_REQUEST = 'FETCH_APARTMENTSRENT_REQUEST';
export const FETCH_APARTMENTSRENT_SUCCESS = 'FETCH_APARTMENTSRENT_SUCCESS';
export const REMOVE_APARTMENTRENT         = 'REMOVE_APARTMENTRENT';
export const VIEW_APARTMENTRENT           = 'VIEW_APARTMENTRENT';
