export const FETCH_SOURCES_FAILURE = 'FETCH_SOURCES_FAILURE';
export const FETCH_SOURCES_REQUEST = 'FETCH_SOURCES_REQUEST';
export const FETCH_SOURCES_SUCCESS = 'FETCH_SOURCES_SUCCESS';
export const REMOVE_SOURCE         = 'REMOVE_SOURCE';
export const VIEW_SOURCE           = 'VIEW_SOURCE';
