export const FETCH_OFFICES_FAILURE = 'FETCH_OFFICES_FAILURE';
export const FETCH_OFFICES_REQUEST = 'FETCH_OFFICES_REQUEST';
export const FETCH_OFFICES_SUCCESS = 'FETCH_OFFICES_SUCCESS';
export const REMOVE_OFFICE         = 'REMOVE_OFFICE';
export const VIEW_OFFICE           = 'VIEW_OFFICE';
