export const FETCH_DEALS_FAILURE = 'FETCH_DEALS_FAILURE';
export const FETCH_DEALS_REQUEST = 'FETCH_DEALS_REQUEST';
export const FETCH_DEALS_SUCCESS = 'FETCH_DEALS_SUCCESS';
export const REMOVE_DEAL         = 'REMOVE_DEAL';
export const VIEW_DEAL           = 'VIEW_DEAL';
