export const FETCH_APARTMENTSSELL_FAILURE = 'FETCH_APARTMENTSSELL_FAILURE';
export const FETCH_APARTMENTSSELL_REQUEST = 'FETCH_APARTMENTSSELL_REQUEST';
export const FETCH_APARTMENTSSELL_SUCCESS = 'FETCH_APARTMENTSSELL_SUCCESS';
export const REMOVE_APARTMENTSELL         = 'REMOVE_APARTMENTSELL';
export const VIEW_APARTMENTSELL           = 'VIEW_APARTMENTSELL';
