export const FETCH_DEPARTMENTS_REQUEST = 'FETCH_DEPARTMENTS_REQUEST';
export const FETCH_DEPARTMENTS_SUCCESS = 'FETCH_DEPARTMENTS_SUCCESS';
export const FETCH_DEPARTMENTS_FAILURE = 'FETCH_DEPARTMENTS_FAILURE';
export const REMOVE_DEPARTMENT         = 'REMOVE_DEPARTMENT';
export const VIEW_DEPARTMENT           = 'VIEW_DEPARTMENT';

export const SET_DEPARTMENTSMANAGEMESSAGE = 'SET_DEPARTMENTSMANAGEMESSAGE';
