export const FETCH_ADDRESS_BY_ID_FAILURE = 'FETCH_ADDRESS_BY_ID_FAILURE';
export const FETCH_ADDRESS_BY_ID_REQUEST = 'FETCH_ADDRESS_BY_ID_REQUEST';
export const FETCH_ADDRESS_BY_ID_SUCCESS = 'FETCH_ADDRESS_BY_ID_SUCCESS';
