export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const GET_CATEGORYINFO_REQUEST = 'GET_CATEGORYINFO_REQUEST';
export const GET_CATEGORYINFO_SUCCESS = 'GET_CATEGORYINFO_SUCCESS';
export const GET_CATEGORYINFO_FAILURE = 'GET_CATEGORYINFO_FAILURE';

export const GET_POSITIONARR_REQUEST = 'GET_POSITIONARR_REQUEST';
export const GET_POSITIONARR_SUCCESS = 'GET_POSITIONARR_SUCCESS';
export const GET_POSITIONARR_FAILURE = 'GET_POSITIONARR_FAILURE';

export const REMOVE_CATEGORY     = 'REMOVE_CATEGORY';
export const SET_CATEGORYMESSAGE = 'SET_CATEGORYMESSAGE';
export const VIEW_CATEGORY       = 'VIEW_CATEGORY';