export const FETCH_COMMERCIAL_PROPERTY_FAILURE = 'FETCH_COMMERCIAL_PROPERTY_FAILURE';
export const FETCH_COMMERCIAL_PROPERTY_REQUEST = 'FETCH_COMMERCIAL_PROPERTY_REQUEST';
export const FETCH_COMMERCIAL_PROPERTY_SUCCESS = 'FETCH_COMMERCIAL_PROPERTY_SUCCESS';
export const REMOVE_COMMERCIAL_PROPERTY        = 'REMOVE_COMMERCIAL_PROPERTY';
export const VIEW_COMMERCIAL_PROPERTY          = 'VIEW_COMMERCIAL_PROPERTY';
