export const FETCH_USERNOTES_FAILURE = 'FETCH_USERNOTES_FAILURE';
export const FETCH_USERNOTES_REQUEST = 'FETCH_USERNOTES_REQUEST';
export const FETCH_USERNOTES_SUCCESS = 'FETCH_USERNOTES_SUCCESS';
export const POST_USERNOTE           = 'POST_USERNOTE';
export const REMOVE_USERNOTE         = 'REMOVE_USERNOTE';
export const VIEW_USERNOTE           = 'VIEW_USERNOTE';
