export const FETCH_HOUSES_FAILURE = 'FETCH_HOUSES_FAILURE';
export const FETCH_HOUSES_REQUEST = 'FETCH_HOUSES_REQUEST';
export const FETCH_HOUSES_SUCCESS = 'FETCH_HOUSES_SUCCESS';
export const REMOVE_HOUSE         = 'REMOVE_HOUSE';
export const VIEW_HOUSE           = 'VIEW_HOUSE';
